# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Love Alert' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Love Alert
  pod 'Firebase/Analytics'

  target 'Love AlertTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Love AlertUITests' do
    # Pods for testing
  end

end
